### PR TITLE
Update Rus Language

### PR DESCRIPTION
**Pull request by 2DKillah**
Update Rus Language

### CODE REVIEW

**Comment by datedufit** [comment]
duplicate.

**Comment by 2DKillah** [comment]
Why duplicate? Why unmerged?
In first "patch" I'm translated starting text (from "novice") and it's
merged.

In second "patch" I'm translated from "valkyrie".

What's happening wrong?

I'm should translate all text in one edit? I can, ok, but i need little bit
time for this.

вт, 19 янв. 2021 г., 06:59 datedufit <notifications@github.com>:

**Comment by datedufit** [comment]
sorry.
i reopen and merge the translate.

**Comment by 2DKillah** [comment]
Got it, thanks! Sorry for late answer. My gmail has a problem. Now it's
nice and I can continue.

ср, 20 янв. 2021 г. в 04:38, datedufit <notifications@github.com>:

**Comment by 2DKillah** [comment]
And I want say one little detail. I don't know context of words in game.
That's why I should make translating patches when file will be ready. I am
should test russian language in game before patch will be finally done. Ok?

One shot isn't critical headshot)))

ср, 20 янв. 2021 г. в 04:38, datedufit <notifications@github.com>:

**Comment by datedufit** [comment]
Sure.

I was developed an auto translate using google translate.
You could just edit the translated text was not right.
And translate the new one.

it's maybe will easier.

**Comment by 2DKillah** [comment]
Sure. Thanks)

вт, 2 февр. 2021 г., 09:34 datedufit <notifications@github.com>:

**Pull request merged**
